networks:
  app-network:
    driver: bridge

services:
  backend:
    image: hojiakbar2806/rent_cars_backend
    container_name: backend
    command: /bin/sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env  
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    image: hojiakbar2806/rent_cars_frontend
    container_name: frontend
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network


  nginx:
    image: nginx:latest
    container_name:  nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "85:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./nginx/error-pages:/usr/share/nginx/html  
    networks:
      - app-network