networks:
  rent_cars_network:
    driver: bridge
  database_network:
    external: true

services:
  rent_car_backend:
    image: hojiakbar2806/rent_cars_backend
    command: /bin/sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - rent_cars_network
      - database_network

  rent_car_frontend:
    image: hojiakbar2806/rent_cars_frontend
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - rent_cars_network

  rent_car_nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - rent_car_frontend
      - rent_car_backend
    ports:
      - "85:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/error-pages:/usr/share/nginx/html
    networks:
      - rent_cars_network
