"""fix cascading

Revision ID: b83cd46ad6a6
Revises: 2ab317b4ec3f
Create Date: 2025-05-05 09:57:37.922020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83cd46ad6a6'
down_revision: Union[str, None] = '2ab317b4ec3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'car_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('cars_car_type_id_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'car_types', ['car_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_car_type_id_fkey', 'cars', 'car_types', ['car_type_id'], ['id'])
    op.alter_column('cars', 'car_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
