"""initial tables

Revision ID: d5c50608a869
Revises: ce06f5a87a57
Create Date: 2025-02-23 10:27:31.375017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c50608a869'
down_revision: Union[str, None] = 'ce06f5a87a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_car_types_id'), 'car_types', ['id'], unique=False)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('gas_capacity', sa.Integer(), nullable=False),
    sa.Column('drive_mode', sa.Enum('MANUAL', 'AUTO', 'HYBRID', name='drivemode'), nullable=False),
    sa.Column('person_capacity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('car_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_type_id'], ['car_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_car_types_id'), table_name='car_types')
    op.drop_table('car_types')
    # ### end Alembic commands ###
